<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_fortawesome_fontawesome-free_css_all_css-node_modules_bootstrap_dist_css-f575f4.css',
                '/build/app.css',
            ],
        ],
    ],
],

]];
